//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Mahc_Final.Metadata;

namespace Mahc_Final.DBContext
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(CarouselMetadata))]
    public partial class CarouselImage
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public bool Show { get; set; }
    }
}
