//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahc_Final.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactu
    {
        public int Id { get; set; }
        public string VisitorEmail { get; set; }
        public string VisitorName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Question { get; set; }
        public string Reply { get; set; }
    }
}
