//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahc_Final.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorAvailability
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorAvailability()
        {
            this.book_an_appointment = new HashSet<book_an_appointment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> dr_id { get; set; }
        public Nullable<System.DateTime> avail_date { get; set; }
        public string time { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book_an_appointment> book_an_appointment { get; set; }
        public virtual doctor doctor { get; set; }
    }
}
