//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahc_Final.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERWaitTime
    {
        public string Lock { get; set; }
        public int CurrentWaitTime { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int WaitingPatients { get; set; }
    }
}
