//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahc_Final.DBContext
{
    using System;
    using System.Collections.Generic;
     using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Gift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gift()
        {
            this.Orders = new HashSet<Order>();
        }
    
       public int Id { get; set; }
        [Required]

        [Display(Name = "Gift Category")]
        public int cat_id { get; set; }
        [Required]
        [StringLength(255, ErrorMessage = "Name must be at least 2 characters", MinimumLength = 2)]
        [Display(Name = "Gift Title")]
        public string name { get; set; }
        [Required(ErrorMessage = "Please, provide the description for Gift!")]
        [DataType(DataType.MultilineText)]
        [UIHint("tinymce_jquery_full"), AllowHtml]//For editor template
        [Display(Name = "Description")]
        public string desc { get; set; }


        [Display(Name = "Image")]

        public string image { get; set; }
        [Required]

        [Display(Name = "Price in CAD")]
        public Nullable<decimal> price { get; set; }
    
        public virtual GiftCat GiftCat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
