//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahc_Final.DBContext
{
    using System;
    using System.Collections.Generic;
     using System.ComponentModel.DataAnnotations;
    
    public partial class GiftCat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiftCat()
        {
            this.Gifts = new HashSet<Gift>();
        }
    
        public int Id { get; set; }
         [Required]
        [StringLength(255, ErrorMessage = "Category must be at least 2 characters", MinimumLength = 2)]
        [Display(Name = "Gift Category")]
        public string cat_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gift> Gifts { get; set; }
    }
}
