using System.ComponentModel.DataAnnotations; /* NOT TO LOSE DATA ANOTATIONS*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahc_Final.DBContext
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(Models.Job_applicationsMetadata))] /* NOT TO LOSE DATA ANOTATIONS*/
    public partial class Job_applications
    {
        public int Id { get; set; }
        public int Job_id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CV { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
