//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahc_Final.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string sender_first_name { get; set; }
        public string sender_last_name { get; set; }
        public string sender_phone { get; set; }
        public string sender_email { get; set; }
        public string patient_first_name { get; set; }
        public string patient_last_name { get; set; }
        public string patient_phn_num { get; set; }
        public int gift_id { get; set; }
        public string message { get; set; }
    
        public virtual Gift Gift { get; set; }
    }
}
