//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahc_Final.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff1
    {
        public int Id { get; set; }
        public int dept_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public Nullable<decimal> phone { get; set; }
        public string email { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
