//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahc_Final.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Volunteers = new HashSet<Volunteer>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public System.DateTime Time { get; set; }
        public string Regularity { get; set; }
        public string Desc { get; set; }
        public bool Status { get; set; }
        public string Contact_person { get; set; }
        public string Contact_phone { get; set; }
        public System.DateTime Created_date { get; set; }
        public int Created_by { get; set; }
        public System.DateTime Modified_date { get; set; }
        public int Modified_by { get; set; }
    
        public virtual HosMember HosMember { get; set; }
        public virtual HosMember HosMember1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Volunteer> Volunteers { get; set; }
    }
}
